config/routes.rb
StuffWhitePeopleDid::Application.routes.draw do
  root to: 'home#index'
  match 'activity' => 'home#activity', as: :activity
  
  match 'me/:action' => 'home'
  resources :accomplishments, :only => [:update, :destroy]

  resources :users, :only => [:index, :show]
  resources :posts, :only => [:index, :show]
end

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<head>
  <%= stylesheet_link_tag 'reset', 'layout', controller_name %>
  <%= javascript_include_tag 'jquery', 'swpd' %>
  <title>Stuff White People Did</title>
</head>
<body>
  <div id="banner">
    <div id="header" class="body">
      <%= link_to 'Stuff White People Did', root_path, :class => 'title' %>
      <div id="menu">
        <% if facebook_connected? %>
          <%= facebook_picture(facebook_uid, :height => 28) %>
        <% end %>
        <fb:login-button></fb:login-button>
      </div>
    </div>
  </div>
  <div id="content" class="body">
    <%= yield %>
  </div>
  <%= render 'shared/facebook_js' %>
</body>
</html>

app/views/layouts/swpd.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
  <%= stylesheet_link_tag 'reset', 'layout', controller_name %>
  <%= javascript_include_tag 'jquery', 'rails', 'swpd' %>
  <%= csrf_meta_tag %>
  <!--[if IE 7]>
  	<%= stylesheet_link_tag 'ie7' %>
  <![endif]-->
  <title>Stuff White People Did</title>
</head>
<body>
  <div id="banner">
    <div id="header" class="body">
      <%= link_to 'Stuff White People Did', root_path, :class => 'title' %>
      <div id="menu">
        <% if fb.connected? %>
          <%= link_to 'Home', root_path %>
          <%= link_to 'Full List of White Stuff', posts_path %>
          <%= link_to 'Recent White Activity', activity_path %>
        <% else %>
          <fb:login-button></fb:login-button>
        <% end %>
      </div>
    </div>
  </div>
  <div id="content" class="body">
    <%= yield %>
  </div>
  <%= render 'shared/facebook_js' %>
  <%= render 'shared/analytics' %>
</body>
</html>